# Generated by Django 2.1.3 on 2018-12-02 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='message',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='name',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='subject',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(max_length=256),
        ),
    ]
